try {
  a
} catch(e) {}
console.log('a')